wirecardBrasil/moip-sdk-php

- README.md
If the developer follow the example of reademe.md the error displays of "Call to undefined method Moip\Moip::customer()"
This pull request fix this
> fixed undefined method error following the example of README.md

- src/Moip/Resource/Orders.php
The method getStatus was returning NULL, add status in $order->data
> set status in populate method

- src/Moip/Http/AbstractHTTPRequest.php
- src/Moip/Http/AbstractHttp.php
- src/Moip/Http/CURL.php
- src/Moip/Http/HTTPConnection.php
- src/Moip/Http/HTTPCookieManager.php
- src/Moip/Http/HTTPRequest.php
- src/Moip/Http/HTTPResponse.php
- src/Moip/Resource/Customer.php
- src/Moip/Resource/Entry.php
- src/Moip/Resource/MoipResource.php
- src/Moip/Resource/Multiorders.php
- src/Moip/Resource/Orders.php
- src/Moip/Resource/Payment.php
- src/Moip/Resource/Refund.php
@SOSTheBlack requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/moip/moip-sdk-php/
> Scrutinizer Auto-Fixes

- src/Moip.php
- src/Resource/Customer.php
- src/Resource/MoipResource.php
- src/Resource/Multiorders.php
- src/Resource/Orders.php
- src/Resource/Payment.php
Meu pull request anterior acabou formatando o código fonte de maneira errada. Este corrige o erro anterior.
> Fix formatting style

- src/Link.php
- src/Links.php
- src/Moip.php
- src/Resource/Customer.php
- src/Resource/MoipResource.php
- src/Resource/Orders.php
- src/Resource/Transfers.php
- tests/MoipTest.php
- tests/MoipTestCase.php
- tests/Resource/PaymentTest.php
Essa pull request resolve o issue #58.
Algumas observações: 
- Eu coloquei a classe `Links` e `Link` na raiz da pasta src seguindo o "padrão" do projeto, porém minha opinião é de que essas classes (e outras classes que também estão na raiz) deveriam ir em uma pasta mais organizada (por exemplo: "Api", "Objects", etc) 
- Foram corrigidos pequenos bugs de typos e etc 
- Foi adicionado um unit test realizando um pagamento por boleto
- Foi adicionado um unit test para a função `getLinks`
> Adiciona o método getLinks() a classe MoipResource

- src/Moip.php
- src/Resource/Account.php
- tests/MoipTest.php
- tests/MoipTestCase.php
Add **Account Resource** to create an account in Moip through API.
> Account resource

- src/Resource/Payment.php
Adicionar o método para recuperar o status do pagamento.
> Add getStatus() in Moip\Resource\Payment

- README.md
> Correção no link para documentação da API

- src/Resource/Orders.php
Define o id próprio ao popular a classe orders.
> Ajuste na classe Orders

- src/Resource/Orders.php
Adiciona corretamente os dados do cliente ao popular a classe Orders.
> Ajuste nos dados do cliente

- src/Resource/Refund.php
Added a way to retrieve the Refund ID (eg "REF-693JHTD5P872").
> Added getId to Refund

- src/Resource/Multiorders.php
Concerto do get do multipedidos.
> Concerto do get do multipedidos.

- src/Resource/Orders.php
add method for set UrlSuccess and UrlFailure and add method for  get checkoutPreferences
> add set redirectUrls & add get CheckoutPreferences

- src/Resource/Refund.php
- tests/Resource/RefundTest.php
- tests/TestCase.php
Fixed generated json to refund request and created tests to bank account refund methods.
> Fix bank account refund

- src/Resource/Payment.php
- tests/Resource/PaymentTest.php
- tests/Resource/RefundTest.php
Adding payment simulator to payments using credit card payment with status IN_ANALYSIS and billet payment with status WAITING and flag to store credit card.
> Adding payment simulator and flag to store credit card

- src/Resource/Orders.php
- tests/Resource/OrdersTest.php
Fixing installment of checkout preferences to receive set of installment instead just one.
> Fixing installments of checkout preferences

- src/Resource/MoipResource.php
> Fix getdatetime

- CHANGELOG.md
Creating changelog to repo \o/
> docs: Create changelog

- src/Resource/Account.php
- tests/Resource/AccountTest.php
Preventing account from create with company node when it was not set.
> fix(Account): Fix account create without company set

- CHANGELOG.md
- src/Moip.php
This PR updates the repo and sets the final commit for tagging a v1.3.1 hotfix.
> [RELEASE] v1.3.1

- CHANGELOG.md
- src/Moip.php
PR to release new version with changes in #165 and #167.
> [RELEASE] v1.3.2

- src/Resource/Customer.php
- src/Resource/Orders.php
- tests/Resource/CustomerTest.php
Prevent notice when tax document or receivers are not returned
> Bugfix: Orders

- README.md
https://github.com/moip/moip-sdk-php/issues/202
Could not find any references to setDelayCapture(true) in the readme
> removed unnecessary setDelayCapture calls

- src/Resource/Orders.php
- src/Resource/Transfers.php
- tests/Resource/TransfersTest.php
- tests/TestCase.php
Criar transferência para uma conta salva previamente e adiciona a categoria do item no pedido.
> Transferência para conta salva e categoria de item

- README.md
- src/Resource/Balances.php
Fixes holder example, on `README.md` (**Pagamentos** -> **Inserir dados do portador**).
> Fixes holder example

- README.en.md
Adds an English version of `README.md`.
> Adds English version of README.md

- README.en.md
Fix typing error on `README.en.md`.
> Fix typing error - README.en.md
